# https://github.com/golangci/golangci-lint/blob/master/.golangci.reference.yml
run:
  skip-files:
    - main.go
linters:
  enable-all: true
  disable:
    - gomnd
    - nonamedreturns
    - wsl
    - varnamelen
